name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Prepare - Checkout
        uses: actions/checkout@v2
      - name: Prepare - Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Prepare - Install dependencies
        run: npm install
      - name: Build
        run: npx sapper export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./__sapper/export
          publish_branch: gh-pages
          cname: fabric.falseresync.ru
